# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python34"
      TOX_ENV: "py34"

    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"

init:
  # Check that we have the expected version and architecture for Python
  - "%PYTHON%/python -V"
  - '%PYTHON%/python -c "import struct;print(8 * struct.calcsize(''P''))"'

install:
  # Use `python -m pip` to avoid `Access is denied` error
  - "%PYTHON%/python -m pip list"
  - "%PYTHON%/python -m pip install -U setuptools pip virtualenv tox wheel"

build: false # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox -e %TOX_ENV%"

after_test:
  - "%PYTHON%/python setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*
